site_name: Whistle Drywall App Knowledge Base
site_url: https://knowledge-base-whistledrywallapp.netlify.app/
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

  - Bills:
      - Create and Manage Your Bills: Bills/create-and-manage-your-bills.md

  - Change Order Request:
      - Create a Change Order Request: Change Order Request/Create-a-Change-Order-Request.md

  - Invoices:
      - Managing Your Invoices: Invoices/managing-your-invoices.md

  - Jobs:
      - Job Creation: Jobs/job-creation.md
      - Uploading Your Budgets and SOV: Jobs/uploading-your-budgets-and-sov.md

  - Purchase Orders:
      - Creating and Managing Your Purchase Orders: Purchase Orders/creating-and-managing-your-purchase-orders.md

  - Teams:
      - Creating and Managing Your Teams: Teams/creating-and-managing-your-teams.md


  - User Management:
      - Creating and Managing Users: User Management/creating-and-managing-users.md

  - Vendors:
      - Creating and Managing Your Vendors: Vendors/creating-and-managing-your-vendors.md

  - Worker Contracts:
      - Creating and Managing Worker Contracts: Worker Contracts/creating-and-managing-worker-contracts.md

  - Latest Updates:
      - Whatâ€™s New: Latest Updates/whats-new.md


theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.top
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
    - content.metadata
    - content.tabs.link
    - content.code.copy

  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
      primary: custom
      accent: blue

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 2
  - tables

plugins:
  - glightbox
  - tags
  - search:
      lang: en

copyright: |
  &copy; 2025 | Whistle Coding LLC and Whistle Drywall App | all rights reserved